version: "3.8"
services:
  db:
    image: postgres:15
    container_name: postgres_ai_assistant
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_ai_assistant_network

volumes:
  postgres_data:
